options:
  dcf_path: "@BUS_CONFIG_PATH@"

master:
  node_id: 1
  driver: "ros2_canopen::MasterDriver"
  package: "canopen_master_driver"
  sync_period: 10000

defaults:
  dcf: "cia402_slave.eds"
  driver: "ros2_canopen::Cia402Driver"
  package: "canopen_402_driver"
  period: 10 # 1 ms
  heartbeat_producer: 1000 # Heartbeat every 1000 ms
  position_mode: 1 # Profile Position Mode
  sdo: # SDO executed during config
        - {index: 0x6081, sub_index: 0, value: 1000} # Set Profile Velocity
        - {index: 0x6083, sub_index: 0, value: 10000} # Set Profile Acceleration
        - {index: 0x6084, sub_index: 0, value: 10000} # Set Profile Deceleration
        - {index: 0x6085, sub_index: 0, value: 10000} # Set Quickstop Deceleration
        - {index: 0x6098, sub_index: 0, value: 0} # Set default Homing Method to 0 (No homing operation required)
        - {index: 0x60C2, sub_index: 1, value: 50} # Set Interpolation Time Period Value to 50 ms
        - {index: 0x60C2, sub_index: 2, value: -3} # Set Interpolation Time Index to 10-3s
  tpdo:
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x6041, sub_index: 0} # Statusword
        - {index: 0x6061, sub_index: 0} # Modes of Operation Display
    2:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x6064, sub_index: 0} # Position Actual Value
        - {index: 0x606C, sub_index: 0} # Velocity Actual Value
    3:
      enabled: false
    4:
      enabled: false
  rpdo:
    1:
      enabled: true
      cob_id: "auto"
      mapping:
      - {index: 0x6040, sub_index: 0} # Controlword
      - {index: 0x6060, sub_index: 0} # Modes of Operation
    2:
      enabled: true
      cob_id: "auto"
      mapping:
      - {index: 0x607A, sub_index: 0} # Target Position
      - {index: 0x60FF, sub_index: 0} # Target Velocity
    3:
      enabled: false
    4:
      enabled: false

nodes:
  joint_1:
    node_id: 2
  joint_2:
    node_id: 3
  joint_3:
    node_id: 4
  joint_4:
    node_id: 5
  joint_5:
    node_id: 6
  joint_6:
    node_id: 7
  joint_7:
    node_id: 8